version: '3.8'

services:
  data-service:
    build:
      context: ./data-service
    ports:
      - "4000:4000"
  
  frontend-service:
    build:
      context: ./frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - data-service

  scraper-service:
    build:
      context: ./scraper-service
    depends_on:
      - data-service